### ISSUE TITLE
unreliable on ESR 52.6.0

### ISSUE THREAD

**Issue by archenemies** [docwhat/itsalltext#100]
I am dependent enough on this add-on that I have switched to using a binary Firefox 52.6.0 ESR. Everything was working OK until I ntoiced that Firefox had updated itself to some huge version in the background. So I had to untar the package again and `chmod a-w` and do various other configuration changes to prevent updates. I also disabled AdBlock Plus which was taking 100% CPU on a minimal web page.

Now for some reason IAT is not reliable. I can get it to work by removing it and reinstalling it, but often I don't see a button for text boxes, ctrl key doesn't work, etc.

Any ideas? By the way, thank you for making my life better for so many years...

**Comment by archenemies** [comment]
Actually, today I noticed that the edit button appears after I leave the tab and come back to it... That is something I can work around, but I wonder why it is happening.

**Comment by docwhat** [comment]
Sorry. I’m really not interested any more. 

I’ll accept any PR you want to send me; heck, I’d probably just make you a contributor. 

There are manual tests you can run and debugging described in the text files. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by archenemies** [comment]
Yeah, thank you, I was looking at your debugging document when I saw the button appear again.

Either way ... it looks like you have plenty of contributors in case you want to go join a monastery, but I would promise not to abuse my power (and probably never use it either, but who knows!).

Thanks.

**Comment by archenemies** [comment]
After playing around with profiles I decided that this issue was probably caused by having run a newer version of Firefox on the default profile directory. Doing so causes all sorts of havoc - extensions are disabled, SQLite databases are upgraded and apparently can no longer be read by the older (52 ESR) version (?). Reverting these changes manually is next to impossible. One of those changes, but I'm not sure which, apparently disables Itsalltext! in a way that makes it hard to "re-enable" through the GUI. Since I still want to have the latest version of Firefox installed through my distro for testing, I wanted to safeguard against the new version accidentally clobbering my profile directory in the future. What I did was the following:

1. Create a new profile for day-to-day use with Firefox ESR (copying as much stuff as possible - bookmarks, history database, etc. from a working backup of the current profile).

2. Make sure the new profile is **NOT** configured to be the default profile. That way if I accidentally start up a more recent Firefox binary, it will use a different profile, and not tamper with the one that I care about.

3. Create a script called "firefox" which starts Firefox ESR and points it to my newly created profile directory:

       $ cat =firefox
       #!/bin/zsh

       $HOME/packages/firefox/firefox-bin -P my_main_but_not_default_profile "$@"

   The idea is that any other scripts or keybindings I have which cause "firefox" to open, as well as any invocations of "firefox" on the command-line, will go through this wrapper scrpt.

That's been working pretty well for me. Note that I've set the entire directory containing firefox-bin to be read-only. This is important because sometimes if I leave Firefox open for a long time then it mysteriously switches to my "default" profile and complains that it is unable to upgrade because of lacking permissions. (I have "app.update.auto"="false")

FWIW I tried "Textern" and it was a decent replacement for IAT, at least it did not seem laggy or anything. But I wanted to solve this problem I had with preserving the functionality of Firefox ESR.
