### ISSUE TITLE
Hard to find Temporary Files

### ISSUE THREAD

**Issue by robertII** [docwhat/itsalltext#37]
IAT is great -- I use it a lot.  BUT...

My editor crashed while working on an IAT document, and I've had to spend over an hour finding the file the editor was actually working on, so that I could retrieve the latest saved state.

Why isn't this visible somewhere?

"Store working files HERE" would be a natural preference.   Even if you don't let me change it, at least display it somewhere --- e.g. the preferences page.

**Comment by barrycarter** [comment]
For those who find this page looking for the answer to the question "where does itsalltext store its temp files", the answer is: $HOME/.mozilla/firefox/YOUR_PROFILE_ID/itsalltext/
