### ISSUE TITLE
IAT updates text but web page not sensing the update as a real update

### ISSUE THREAD

**Issue by bgoodr** [docwhat/itsalltext#51]
This issue affects multiple websites, two of which are:

1. Review Board (http://www.reviewboard.org/)
2. StackExchange websites (http://electronics.stackexchange.com/)

The example below is given the StackExchange website, but my belief is that the problem is not specific to that website:

Steps to reproduce:
======================

Navigate to http://electronics.stackexchange.com/posts/46913/edit  and edit it (we won't commit the edit, this is just to demonstrate the issue).

Move your cursor over the IAT Edit button and click it (this is presuming IAT is already configured and working for most other websites).

In your editor outside of the browser, insert some text at the top of the IAT generated file, and save it. IAT should sense it and update it back into the web browser at this time.

Switch focus back to the browser window.  

Scroll down and notice that the text field (in the TEXTAREA) has been updated. That is expected behavior so far.

However, scroll down past the TEXTAREA part of the web page, and notice that the old text is still there. That should have been updated and it is not updated to reflect the change.

Now, click inside the text area in the web browser, type a single SPACEBAR key, and then BACKSPACE key (i.e., just make a real edit outside of IAT and then undo it). Notice that the web page senses it now and updates the rest of of the text in the web page below that text area.

Of course, that indicates the workaround I have been using, but that workaround effectively defeats most of the usefulness of IAT on these particular websites as it forces you to do cumbersome and special steps to force the full and complete update just as if the user typed in the text directly into the TEXTAREA in the web page itself.

**Comment by docwhat** [comment]
This should be fixed by commit 9b9187 -- It'll go out in version 1.9.0 which will be released as soon as AMO accepts it and it is reviewed.
