### ISSUE TITLE
Prevent Working Directory being set to $HOME

### ISSUE THREAD

**Issue by Flimm** [docwhat/itsalltext#52]
I set the working directory to my home directory. Now every time I launch firefox, my `~/.bashrc` file (which is a symlink to another file) gets deleted.

**Comment by docwhat** [comment]
Version 1.9.0 will have an updated preferences, complete with a warning.  So hopefully nobody else will get bit by this bug.

It should be out as soon as AMO fixes their upload validator and it is reviewed.

**Comment by Flimm** [comment]
Thanks @docwhat!
