### ISSUE TITLE
Breaks Facebook

### ISSUE THREAD

**Issue by mcepl** [docwhat/itsalltext#54]
One of the many reasons I hate Facebook (and even more I hated that I am forced by my friends to use it) is that they break Enter key in the comment box. I have to edit in $EDITOR to insert new paragraph. So, I thought “Stand back, I know about itsalltext!” ... but unfortunately Facebook requires broken behavior, so that with itsalltext it is broken and I cannot enter the edited text into Facebook page.

http://mcepl.fedorapeople.org/tmp/itsalltext-facebook.webm

**Comment by docwhat** [comment]
Cool video!

Unfortunately, Facebook doesn't use "textareas" in a normal way... there isn't much I can do about it from within IAT without reverse engineering facebook's status update thingy... and they change it regularly, it'd be a full time job. :-(

Sorry. I don't think I can fix this. :-(
