### ISSUE TITLE
editor refuses to update 'readonly' file

### ISSUE THREAD

**Issue by rretter** [docwhat/itsalltext#63]
Using Firefox 35.0.1 and vim7.3 under Windows 7 Pro SvcPk 1.

Bring up editor upon textbox contents by means of either context menu or button.  Editor launches with correct text content.  However, when saving work is attempted, editor complains:

'readonly' option is set for "blah.domain.com.231x2s1g26.txt". Do you wish to write anyway?

But after confirming intention to write, the writing fails with:

E212: Can't open file for writing

![capture](https://cloud.githubusercontent.com/assets/7855308/6052204/e8726794-ac84-11e4-9099-4569f9705300.JPG)

**Comment by docwhat** [comment]
What is the full path for "Working Directory" (which will be renamed to "Cache Director" in 1.9.0)?

I'm not super familiar with Windows but if that directory is special in any way, then it might cause this behavior.  IAT should create the directory if it doesn't exist already.

What happens if you just set the path to `C:\Users\robr\AppData\IAT`?

**Comment by rretter** [comment]
Thank you.  The suggestion of "just set the path to C:\Users\robr\AppData\IAT" worked.

Which is, of course, good -- but it doesn't really address the issue of why IAT would have chosen an inappropriate folder location in the first place.

**Comment by docwhat** [comment]
Well, Windows has lots of "special" directories and Firefox doesn't have an easy way to query the permissions of directories and files... in fact, Windows permissions (ACLs) are really complicated.

What was the directory set to before? I see "Roaming" in the path... Is that a special directory like the old Windows "suitcase" directory?  If so, that may be why.

**Comment by xOneca** [comment]
I suppose it is where Firefox stores profile data by default:

    Users\<user>\AppData\Roaming\Mozilla\Firefox\Profiles\<profile>

IAT creates cache folder by default there.

**Comment by docwhat** [comment]
Huh. It works for me with the default directory last time I checked windows. Weird.
