### ISSUE TITLE
Doesn't work with Gmail?

### ISSUE THREAD

**Issue by 097115** [docwhat/itsalltext#64]
Seems not to work with Gmail's "new" compose "window", am I right? Any workarounds?

**Comment by xOneca** [comment]
See issue #36.

**Comment by 097115** [comment]
**xOneca**,

Thanks a lot (and bad, bad me, haven't found that issue in question myself).

However, the alternative version of the extension, posted at [the end of the thread](https://github.com/docwhat/itsalltext/issues/36#issuecomment-61453504) still has some problems for me, like grabbing the text with HTML codes, something like `<br><br><br><br><br>--<br>097115<br><br><br>` when calling from a new letter (both with rich and plain text options).

**Comment by docwhat** [comment]
Add comments on #36 to see if it can be fixed there.
