### ISSUE TITLE
The 1.90 version is buggy

### ISSUE THREAD

**Issue by andalou** [docwhat/itsalltext#65]
I'm using itsalltext on SeaMonkey 2.32.1 with vim.
Since I updated itsalltext to 1.90, I began having problems with it.
The hot key doesn't work anymore. It only worked the first time. Moreover, when I was editing messages on Facebook, the editor didn't pop up, not even when I launched the editor from the context menu on the textarea.

**Comment by docwhat** [comment]
What OS is this?

I'll be honest, I haven't been testing SeaMonkey. I didn't realize it still existed! :-/

**Comment by andalou** [comment]
It's Windows 7 Home Premium. I'm using SeaMonkey 2.32.1, which, as far as I know, corresponds to Firefox 36.

**Comment by martinym** [comment]
I've already reported this to docwhat.

The Edit button no longer displays in IAT v1.9.0 rendering it unusable.
I'm  running Firefox v31.5.0 ESR on Windows 7 Pro.
Fortunately IAT v1.8.1 still works so I've reverted to it and turned off Automatic Updates for it in Firefox's Add-ons manager.

Here's where you can still get [Version 1.8.1](https://addons.mozilla.org/en-US/firefox/addon/its-all-text/versions/1.8.1) from addons.mozilla.org.

**Comment by docwhat** [comment]
AMO is having [problems again](https://bugzilla.mozilla.org/show_bug.cgi?id=1135471).  As soon as that is resolved and I get it submitted and it is reviewed, it'll be available for general usage.

**Comment by ineuw** [comment]
Thanks martinym for the link to the earlier version. Uninstalled v1.90 and installed 1.81 which works as it should. I am using FF 37.0 beta in Windows 7 Pro. 32bit. I also just noticed your comment docwhat. I hate to tell you but FF 34 - 36 are having a lot of crashes. That's why I decided to go for the beta.

**Comment by docwhat** [comment]
It looks like AMO isn't coming back tonight.  You can directly download [itsalltext-1.9.1.xpi](https://docwhat.org/files/itsalltext-1.9.1.xpi) and install it manually, if you want to try it out before it is available officially.

Ciao!

**Comment by docwhat** [comment]
Whups, tried it one more time and it worked.  So now it just needs to be reviewed. Yay!

**Comment by ineuw** [comment]
sorry docwhat, your link is not working https://docwhat.org/files/itsalltext-1.9.1.xpi, there is a connection failure. But there is no hurry. :-) Thanks anyways.

**Comment by docwhat** [comment]
Man. I can't win for losing.  Try again if you want. It checks out from here and Firefox should handle the increased SSL security fine.

**Comment by ineuw** [comment]
Don't fret! all links to moz are not accessible have connection problems. I tried with other unrelated software. Version 1.91 is already available on the addons list and installed it and works fine.
https://addons.mozilla.org/en-US/firefox/addon/its-all-text/?src=collection&collection_id=603aa7cd-289e-44f8-af17-bc4762165e6e

**Comment by martinym** [comment]
Just got v1.9.1 officially  through addons.mozzila.org and the edit button is back. Yay!

Don't forget to enable Automatic Updates for it again in Firefox's Add-ons manager if you turned then off.

Thanks @docwhat.

**Comment by andalou** [comment]
I tried it and it works almost in all cases. It works on the textarea for "Message" on Facebook, but it doesn't work on the textarea for "Comment."

**Comment by NewMexicoKid** [comment]
Thanks for the 1.9.1 fix! My blue button is back as well.
