### ISSUE TITLE
It does not work on mac

### ISSUE THREAD

**Issue by hexiay** [docwhat/itsalltext#69]
Hello, 

When I try to edit some text on my Firefox, it poped this error out:

"""
I ran this command: /usr/local/bin/mvim /Users/wanhe/Library/Application Support/Firefox/Profiles/ga3jb4uu.default/itsalltext/_Users_wanhe_Downloads_wanhe.html.2c2f2d2r.txt

...and it exited with a status of 1.
"""

Is there any way to fix this? Is it due to a space in the file path?

Thanks,
hewanxiang@gmail.com

**Comment by docwhat** [comment]
I use OS X. I can't reproduce this. I assume you figured out the problem.

**Comment by hexiay** [comment]
Yes, thanks!
It is due to that I created a link to the VIM application in my local path,
I found the link cannot be used as a path as the Firefox it's all edit
external editor path. I have to use the real path for the application.


Thanks,
Wanxiang

On Wed, Mar 11, 2015 at 10:33 PM, Christian Höltje <notifications@github.com
