### ISSUE TITLE
Needs some randomness in filename generation

### ISSUE THREAD

**Issue by phmarek** [docwhat/itsalltext#71]
I recently tried to report a bug (somewhere), and while fetching more information I ran into another bug. So I opened another tab at the same URL; but when I tried to use ItsAllText on that too, my editor (for the previous bug) told me that the file was changed externally (ie. by the new tab).

Please insert some randomness (tab number, thread, $RANDOM, whatever) into the filename.

**Comment by xOneca** [comment]
Please, see discussion in issue #16. (dup?)

**Comment by docwhat** [comment]
Indeed. Dup.
