### ISSUE TITLE
Preferences get reset periodically

### ISSUE THREAD

**Issue by eresonance** [docwhat/itsalltext#77]
I don't know why by my itsalltext preferences keep getting reset every couple days or so. The editor and button preferences get reset to their defaults so I have to set them again every so often.

I'm using firefox v44.0.2.

Do you know why this is happening?

**Comment by docwhat** [comment]
Not a clue; It shouldn't do that.  Does downgrading or upgrading Firefox help?

**Comment by eresonance** [comment]
No, unfortunately it's been doing this for a while. It does it on my machine at work too, could it be some funky interaction with another plugin?

I think the only ones that I have on both machines are:
keepass helper
markdown here
passifox
tabgroups (although it was doing it before using this)
ublock origin

I don't have addon sync enabled...

**Comment by docwhat** [comment]
A new signed version of IAT came out... maybe that will help? I mean, this code has been rock solid for so long, I don't even remember how it works. :-/

**Comment by eresonance** [comment]
I'll give it a try, thanks.

What editor do you normally use with it?

**Comment by eresonance** [comment]
Nah, still getting reset.

I really have no clue what is actually doing the reset. The only common thing between both computers is the fact I use notepad++. I'll try changing the editor and see what happens.

**Comment by eresonance** [comment]
Ok, after a bit of debug, I found it happens after I close and reopen firefox. As soon as I reopen it all my settings for itsalltext have been wiped. I see from the prefs.js file that they are completely missing. I think itsalltext will create a new workingdir and tracker_id when initialized (as I type this), but the rest are missing.

I guess I could override the defaults/preferences/itsalltext.js but that's a bit annoying. Do you think it's firefox that's clearing out my preferences?

**Comment by docwhat** [comment]
Do you have a corporate plugin or something that might enforce preferences?

**Comment by eresonance** [comment]
No, definitely not. It also happens at home, although I should see if preferences are synced, could be related to that...

I'm going to disable all of my plugins except this one and try seeing if the preferences get reset. Very strange issue!

**Comment by eresonance** [comment]
So I don't see this issue anymore! I did the following:
* Started using the firefox developer edition
* Made a new firefox profile
* Made sure to grab the latest itsalltext version

Now I can close and reopen firefox without the settings being reset. I'm guessing the new profile fixed the issue but I can't fully explain why...
