### ISSUE TITLE
"Open in external editor" button is missing when editing a user style for Stylish

### ISSUE THREAD

**Issue by lunarrunner** [docwhat/itsalltext#79]
Under Manjaro Linux, in Firefox 47.0 with It’s All Text 1.9.2, the button *Open in external editor* is completely missing when editing a user style for Stylish (V2.0.6). Where the button is supposed to appear, between the button *Paste* and the checkbox *Line wrap*, there is a big empty space instead.

However, it appears as it should in Pale Moon 26.3.0 using the same versions of these extensions.

**Comment by docwhat** [comment]
This appears to be a problem with the new multi-threaded plugin stuff... I'm not sure how to actually fix it. :sad:

If anyone can help, that'd be great.

**Comment by aleprovencio** [comment]
bla bla bla_jf_
isso mesmo_iieifj_

**Comment by lunarrunner** [comment]
I've found a solution! By following the 2nd and 4th comment under [this](https://github.com/stylish-userstyles/stylish/issues/218) issue, I opened `about:config`, looked for `extensions.stylish.editor` and changed its value from 0 to 1. Now the button appears in Firefox 49 just like in Pale Moon.
