### ISSUE TITLE
Broken with (g)vim

### ISSUE THREAD

**Issue by bpj** [docwhat/itsalltext#82]
itsalltext has recently got issues with (g)vim, which somehow fails to load python when opened by itsalltext, resulting in a flurry of error messages from vim plugins. I tried to give vim the option not to load plugins, but that didn't work.

Vim 8.0 Ubuntu 14.04

**Comment by docwhat** [comment]
It sounds like a `PATH` issue or something.  Try creating a shell script that sets your `PATH` the right way and have IAT call that instead.

**Comment by phmarek** [comment]
vim 8 doesn't have python enabled by default, IIRC. So any plugin that tries to use it will fail.

**Comment by docwhat** [comment]
I'm pretty sure this is a `vim` issue, not an IAT issue... closing.

**Comment by bpj** [comment]
Whatever it was there is no problem now.
