### ISSUE TITLE
Often need to click the 'Edit' button several times

### ISSUE THREAD

**Issue by harl** [docwhat/itsalltext#89]
For some reason, I often haven to click that button three or more times before it actually runs the associated program. The button also often disappears while I'm trying to click it, so those things may or may not be connected.

**Comment by docwhat** [comment]
That sounds like something is conflicting with IAT.  Can you try disabling all plugins except IAT and see if that fixes it?

I have a test-suite I use for manually testing IAT at https://docwhat.org/files/iat/ that you can use to confirm it is working correctly.

**Comment by vgivanovic** [comment]
I have a similar issue. 

The problem seems to go away when IAT is the only add-on which is enabled. Let me see if I can figure out which other add-on has a conflict with IAT.

**Comment by vgivanovic** [comment]
OK, with all my add-ons enabled, I have to click the Edit button twice to get IAT to come up in Emacs (server). ut, if I disable the Todoist add-on, a single click works.

I am now going to try a couple of variations to try and make sure it's the Todoitst add-on which is the culprit.

**Comment by vgivanovic** [comment]
Arrgh. Just re-enabled the Todoist add-on and IAT works as expeccted. (That's good, I suppose, bur frustrating because I'm back to where I started, but everything works when before it didn't.)

**Comment by vgivanovic** [comment]
Arrgh. Just re-enabled the Todoist add-on and IAT works as expeccted. (That's good, I suppose, bur frustrating because I'm back to where I started, but everything works when before it didn't.)

I'm giving up debugging now until the problem re-occurs.

P.S. I don't know what the capabilities of add-ons are, but this kind of situation might benefit from a logging  facility.

**Comment by docwhat** [comment]
@vgivanovic: Yeah.  Unfortunately, the best way to find these kinds of conflicts is to disable them all then enable them one by one until you find the culprit. :-(

If you want to go really nuts, you can use my [DEBUGGING](https://github.com/docwhat/itsalltext/blob/master/DEBUGGING.md) documentation.  It may or may not help with the other extensions, tho.

Closing for now.  Ciao!

**Comment by docwhat** [comment]
Closing issue since it wasn't showing any activity for a long time.
