### ISSUE TITLE
Can I use diferent file extension depending on domain?

### ISSUE THREAD

**Issue by FrancescElies** [docwhat/itsalltext#90]
Let's say I would like to edit some text in jira, for this kind of website the
text format is `jira-markup`. Now I would like to edit a text-box in github, now
I use `markdown`.

If I tell It's all text the extension of the file is `.md` my text editor
automatically recognizes it the extension and it sets up some nice goodies for
markdown, but then I get the wrong file extension for jira.

Is there a way to get different extension file depending on the website I am visiting?

Best wishes, Francesc

**Comment by docwhat** [comment]
Not really.  It will remember the previous value suggested if the cached file isn't cleared, though.
